Algoritmo "exercicio1"
// MARCUS - 1190
// EM CASO DE ERRO, FECHE A FEERRAMENTA OU TIRE OS COMENTARIOS
// EM ALGUNS LUGARES NÃO TEM COMENTARIOS POIS ESTA BUGANDO
Var
nome : caracter
idade : inteiro
nivel : caracter
Inicio
escreva ("Qual seu nome?")
leia (nome)
escreva ("Qual sua idade?")
leia (idade)
escolha (idade)
caso 0 ate 2                                        //VERIFICA A ESCOLHA
     escreva ("Berçario")
caso 3 ate 6                              //VERIFICA A ESCOLHA
     escreva ("Educação infantil")
caso 7 ate 10                                     //VERIFICA A ESCOLHA
     escreva ("Fundamental nivel 1")
caso 11 ate 15                                    //VERIFICA A ESCOLHA
     escreva ("Fundamentar nivel 2")
caso 16 ate 18                                  //VERIFICA A ESCOLHA
     escreva ("Ensino medio")
fimescolha

Fimalgoritmo